version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-1
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - "./data/zookeeper-1:/data"
  zookeeper-2:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-2
    environment:
      ZOO_MY_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"
    volumes:
      - "./data/zookeeper-2:/data"
  zookeeper-3:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-3
    environment:
      ZOO_MY_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"
    volumes:
      - "./data/zookeeper-3:/data"
  kafka-1:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    hostname: kafka-1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "9092:9092"
    volumes:
      - "./data/kafka-1:/var/lib/kafka/data"
  kafka-2:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    hostname: kafka-2
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "9093:9092"
    volumes:
      - "./data/kafka-2:/var/lib/kafka/data"
